# Common {{{
# Hostname to the root
baseURL = ""

# Site title
title = "My New Hugo Site"

# Theme to use (located by default in /themes/THEMENAME/).
# theme = ""

# Enable to turn relative URLs into absolute.
# canonifyURLs = false

# Enable this to make all relative URLs relative to content root
# relativeURLs = true

# Include content already expired.
# buildExpired = false

# Include content with publish date in the future.
# buildFuture = false

# Will disable generation of alias redirects.
# disableAliases = false

# Will disable inject a generator meta tag in the head.
disableHugoGeneratorInject = true

# Enable disabling of all pages of the specified kinds.
disableKinds = [
  # "page",
  # "home",
  # "section",
  # "taxonomy",
  # "taxonomyTerm",
  "RSS"
  # "robotsTXT",
  # "sitemap",
  # "404"
]

# Disable automatic live reloading.
# disableLiveReload = false

# Do not convert the url/path to lowercase
# disablePathToLower = false

# Enable to use emoji.
enableEmoji = true

# Pluralize titles in lists.
# pluralizeListTitles = true

# Maximum number of items in the RSS feed.
# rssLimit = "unlimited"

# The length of text in words to show in a .Summary.
# summaryLength = 70

# When enabled, creates URL of the form /filename.html instead of /filename/.
# uglyURLs = false

# Watch filesystem for changes and recreate as needed
# watch = false
# }}}

# Params {{{
# [params]
# }}}

# SEO {{{
# enableRobotsTXT = false

# Google analytics tracking id.
# googleAnalytics = ""
# }}}

# Imaging {{{
[imaging]
# Default resample filter used for resizing
# resampleFilter = "box"

# Default JPEG quality setting
# quality = 75

# Anchor used when cropping pictures.
# anchor = "smart"

# Default background color. 
# bgColor = "#ffffff"

[imaging.exif]
# includeFields = "PATTERN"
# excludeFields = "PATTERN"
disableDate = true
disableLatLong = true
# }}}

# Languages {{{
languageName = "Japanese"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
# disableLanguages = ["cn", ""]

# defaultContentLanguageInSubdir = false

# make .Summary .WordCount behave correctly for CJK languages.
hasCJKLanguage = true
# }}}

# Module {{{
# [module]
#   noProxy = "none"
#   private = "*.*"
#   proxy = "direct"
#
#   [module.hugoVersion]
#     extended = false
#     max = ""
#     min = ""
#
#   [[module.imports]]
#     disable = false
#     ignoreConfig = false
#     patrh = ""
#
#   [[module.mounts]]
#     source = "content"
#     target = "content"
# }}}

# Footnote {{{
# Prefix for footnote anchors
# footnoteAnchorPrefix = ""

# Text to display for footnote return links
# footnoteReturnLinkContents = ""
# }}}

# Output {{{
# Enable verbose output.
# verbose = true

# Enable verbose logging.
# verboseLog = false
# }}}

# Paging {{{
# Default number of elements per page in pagination.
# paginate = 10

# The path element used during pagination.
# paginatePath = "page"
}}}

# Shortcodes {{{
# enableInlineShortcodes = false

# enableMissingTranslationPlaceholders = false
# }}}

# Log {{{
# log = false
# logFile = ""
# }}}

# privacy {{{
[privacy]
  [privacy.disqus]
  disable = true

  [privacy.googleAnalytics]
  disable = true
  # anonymizeIP = false
  # respectDoNotTrack = false
  # useSessionStorage = false

  [privacy.instagram]
  disable = true
  # simple = false

  [privacy.twitter]
  disable = true
  # enableDNT = false
  # simple = false

  [privacy.vimeo]
  disable = true
  # simple = false

  [privacy.youtube]
  disable = true
  # privacyEnhanced = false
# }}}

# permalinks {{{
# :year        the 4 digit year
# :month       the 2 digit month
# :monthname   the name of the month
# :day         the 2 digit day
# :weekday     the 1 digit day of the week (sunday = 0)
# :weekdayname the name of the day of the week
# :yearday     the 1-3 digit day of the year
# :section     the contents section
# :sections    the contents sections hierarchy
# :title       the contnets title
# :slug        the contents slug or title if no slug is provided in the frontmatter
# :filename    the contents filename

# Example:
#  file: /content/posts/sample-entry.md
#  url:  /2019/01/sample-entry/index.html

# [permalinks]
#   posts = "/:year/:month/:title/"
# }}}

# Sitemap {{{
# [sitemap]
#   changefreq = "monthly"
#   filename = "sitemap.xml"
#   priority = 0.5
# }}}

# Rendering {{{
# ignoreFiles = [
#   "\\.*"
# ]
# }}}
